### ISSUE TITLE
Feautures Request: Android support & Bundle OSVR with Cardboard plugin

### ISSUE THREAD

**Issue by r57zone** [simlrh/OSVR-Cardboard#1]
1. Android head tracking support ([FreePie IMU](https://github.com/Xtreamer/FreePie-DiyHt/blob/master/Lib/Android/com.freepie.android.imu.apk) (better) or [Wireless IMU](https://play.google.com/store/apps/details?id=org.zwiener.wimu).)

To head tracking need to add reading from UDP port 5555 [data from the FreePie IMU](https://github.com/Xtreamer/FreePie-DiyHt/blob/master/Lib/Android/FreePIE%20Android%20IMU/src/com/freepie/android/imu/UdpSenderTask.java#L149) (accelerometer, gyroscope, magnetometer). or Wireless IMU example UDP packet:
890.71558, 3, 0.076, 9.809, 0.565, 4, -0.559, 0.032, -0.134, 5, -21.660,-36.960,-28.140
Timestamp [sec], sensorid, x, y, z, sensorid, x, y, z, sensorid, x, y, z
Sensor id: 3 - Accelerometer (m/s^2); 4 - Gyroscope (rad/s); 5 - Magnetometer (micro-Tesla uT);

2. Bundle OSVR runtime with Cardboard plugin. Install files to path "SteamPath" key in registry "HKEY_CURRENT_USER\Software\Valve\Steam" and create shortcuts OSVR server (with configs, plugins) to desktop or video guide for setup SteamVR with all need drivers OSVR, with all configs ("steamvr.vrsettings" or etc).

Thanks.

**Comment by simlrh** [comment]
I don't have an Android device so I'm not able to develop and test this, but I'll happily take a pull request from anyone that does. The relevant code is at https://github.com/simlrh/OSVR-Cardboard/blob/master/src/TrackingServer.cpp#L112

Number 2 is a wontfix though. The all in one installer does all that anyway I think.

**Comment by r57zone** [comment]
Maybe then add support for [OpenTrack](https://github.com/opentrack/opentrack)? It will not need to be tested and it allows you to configure absolutely everything. OpenTrack support much trackers (Android, Arduino, etc).

To support OpenTrack need change output to "UDP over network", open udp server 4242 port and read data from this. For example [implementation](https://github.com/r57zone/OpenTrack-UDP-receive). 
Package type (all values float):
"x y z yaw pitch roll"
(x y z - do not need to use).
Yaw pitch roll need to convert to quaterion with [this function](https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles).

```
static Quaterniond toQuaternion(double pitch, double roll, double yaw)
{
	Quaterniond q;
	double t0 = std::cos(yaw * 0.5);
	double t1 = std::sin(yaw * 0.5);
	double t2 = std::cos(roll * 0.5);
	double t3 = std::sin(roll * 0.5);
	double t4 = std::cos(pitch * 0.5);
	double t5 = std::sin(pitch * 0.5);

	q.w() = t0 * t2 * t4 + t1 * t3 * t5;
	q.x() = t0 * t3 * t4 - t1 * t2 * t5;
	q.y() = t0 * t2 * t5 + t1 * t3 * t4;
	q.z() = t1 * t2 * t4 - t0 * t3 * t5;
	return q;
}
```

**Comment by simlrh** [comment]
I think the best solution is to end support for OSVR-Cardboard completely in favour of a FreePIE > OSVR plugin.

So FreePIE IMU in the background, Moonlight in the foreground, and FreePIE on the PC receiving data and sending to OSVR. Saves duplicating work in this project and in the mobile app.

The mobile app then only has to scan the QR code and check screen resolution to generate the OSVR config. Might even be able to do that with a web app.

Can't even begin to work on this until July though, busy with paid work
